#ifndef ARENA_VERSION_H
#define ARENA_VERSION_H

#define ARENA_VERSION_MAJOR @PROJECT_VERSION_MAJOR @
#define ARENA_VERSION_MINOR @PROJECT_VERSION_MINOR @
#define ARENA_VERSION_PATCH @PROJECT_VERSION_PATCH @
#define ARENA_VERSION_STRING "1.1.0"

#endif /* ARENA_VERSION_H */
